### ISSUE TITLE
Redundant use of 'instead' in graphics-object spec

### ISSUE THREAD

**Issue by carmacleod** [w3c/graphics-aria#4]
[Spec for `graphics-object` in WAI-ARIA Graphics Module Candidate Rec](https://www.w3.org/TR/2018/CR-graphics-aria-1.0-20180329/#graphics-object)

Should remove one of the instances of `instead` in this sentence:
> Container elements that **instead** represent a collection of disconnected objects should **instead** be given the group or list roles.

**Comment by AmeliaBR** [comment]
Definitely a confusing wording. Thanks for the review. We could probably just drop both cases of "instead", but at least one can go.

**Comment by michael-n-cooper** [comment]
Closing based on above commit.

**Comment by AmeliaBR** [comment]
@michael-n-cooper 

That commit was never merged into master (it would have closed the issue automatically). It's part of pull request #5.

(I don't have write permission on master on this repository.)
